source 'https://rubygems.org'

gem 'capybara'
gem 'pry'
gem 'cucumber', '3.1.2'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
#gem 'cpf_faker'
#gem 'faker'
gem 'allure-cucumber'
gem 'test-unit'
gem 'yard'
gem 'yard-cucumber'
gem 'rspec'
gem 'rest-client'
gem 'ffi'
gem 'pry'
gem 'rake'
gem 'redcarpet'
gem 'rspec-expectations'
gem 'rubocop', require: false