#!/bin/bash
#Dispara os testes
# Author: Valter Teodoro
# --------------------------------------
echo "Inicia os testes..."

echo "Inicializa o  ambiente de Testes"
echo "Instala a biblioteca de report Allure"
npm install allure-commandline

echo "Instala as dependencias do projeto de teste"
bundle install

echo "Incia os testes no chrome"
TAGS="\"${EXEC_TAGS:-"@acceptance and not @wip"}\""
rake run_acceptance[chrome,"${TAGS}"]

echo "Gera relatorio da execução dos testes do chrome"
allure generate allure-results/chrome


echo "Incia os testes no firefox"
TAGS="\"${EXEC_TAGS:-"@acceptance and not @wip"}\""
rake run_acceptance[firefox,"${TAGS}"]

echo "Gera relatorio da execução dos testes do firefox"
allure generate allure-results/firefox


echo "Incia os testes no safari"
TAGS="\"${EXEC_TAGS:-"@acceptance and not @wip"}\""
rake run_acceptance[safari,"${TAGS}"]

echo "Gera relatorio da execução dos testes do safari "
allure generate allure-results/safari


echo "Incia os testes no internet_explorer"
TAGS="\"${EXEC_TAGS:-"@acceptance and not @wip"}\""
rake run_acceptance[Edge,"${TAGS}"]

echo "Gera relatorio da execução dos testes do IE"
allure generate allure-results/Edge


echo "Fim"